spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password: 123456
    timeout: 300ms
#  boot:
#    admin:
#      client:
#        # admin 服务端的地址
#        url: http://localhost:8095
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9999
          predicates:
            - Path=/api/auth/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 展示详情
      show-details: always
jwt:
  tokenHeader: Authorization
  secret: daemumall-gateway
  expiration: 604800
  tokenHead: Bearer
redis:
  database: mall
  key:
    admin: 'ums:admin'
    token: 'ums:token'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

# 过滤不需要认证路径条件
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload